### ISSUE TITLE
Asyn primal-dual algorithms special cases

### ISSUE THREAD

**Issue by wotaoyin** [wotaoyin/cf_paper#1]
@tian2tian2 
- [x] Please mention Remark 6 in the main text (not as a remark) early in that subsection. Say that having just one agent recovers stochastic primal-dual update as a special case. Automatically there is no delay. Cite Combettes-Pesquet's "Stochastic Fejer Monotone...." paper and other related papers.
- [x] Please also mention that sync-parallel coordinate descent is also a special case. 
- [x] Algorithm 1 and Algorithm 2 >> Algorithms 1 and 2
- [x] kappa is defined after its first use?
- [x] use \lambda_{\max} instead of \lambda_{max}
- [x] at the beginning of Appendix D, mention which parts will be new (for Algorithms 1 & 2) and which parts will be straightforward adoption from [51](ARock)

**Comment by TianyuWu89** [comment]
OK. How is sync-parallel coordinate descent a special case? I am thinking sync-parallel is essentially full update.

**Comment by wotaoyin** [comment]
It is m+p agents updating m+p blocks in parallel, no delay. Nothing random. Agree to "sync-parallel is essentially full update". So, our proof would apply.
